Flask_Basic_With_User_Authentication/template_name/main/routes.py
from flask import render_template, url_for, redirect, request, Blueprint, request
from template_name.main.forms import SearchForm
from template_name.models import User


main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home(active_template_name_id=None):
    home_user = User.query.filter_by(username="Sologesang").first()
    if home_user:
        username = home_user.username
    else:
        username = User.query.first().username
    return redirect(url_for('users.profile', username=username))


@main.route("/admin", methods=["GET", "POST"])
def admin():
    search_form = SearchForm()
    if search_form.validate_on_submit():
        search_term = search_form.query.data
        if search_term == "":
            users = User.query.all()
        else:
            users = User.query.filter(User.username.contains(search_term))
        return render_template('admin_console.html', search_form=search_form, users=users)
    all_users = User.query.all()
    return render_template('admin_console.html', search_form=search_form, users=all_users)


@main.route("/about")
@main.route("/impressum")
def impressum():
    return render_template('about.html')

Flask_Basic_With_User_Authentication/template_name/users/routes.py
from datetime import datetime
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from template_name import db, bcrypt
from template_name.models import User
from template_name.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                  RequestResetForm, ResetPasswordForm)
from template_name.users.utils import (save_picture, delete_picture, send_reset_email)


users = Blueprint('users', __name__)


@users.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    # 'SET'
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data.lower(), password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    # 'GET'
    return render_template('register.html', title='Register', form=form)


@users.route('/delete_user/<int:user_id>', methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.is_admin and current_user != user:
        print("USER:        ", user)
        print("CURRENT USER:", current_user)
        db.session.delete(user)
        db.session.commit()
        flash(f"Deleted user: {user}", "success")
    elif current_user == user:
        flash("You cannot delete your own account.", "danger")
    else:
        flash("You don't have the permission to do that...", "danger")
    return redirect(url_for('main.search'))


@users.route('/make_admin/<int:user_id>')
@login_required
def make_admin(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.is_admin:
        user.is_admin = True
        db.session.commit()
        flash(f"Made user admin: {user}", "success")
        return redirect(url_for('main.admin'))
    else:
        flash("You don't have the permission to do that...", "danger")
        return redirect(url_for('main.search'))


@users.route('/revoke_admin/<int:user_id>')
@login_required
def revoke_admin(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.is_admin:
        if current_user != user:
            user.is_admin = False
            db.session.commit()
            flash(f"Revoked admin for user: {user}", "success")
        else:
            flash(f"Cannot revoke admin rights for your own account.", "danger")
        return redirect(url_for('main.admin'))
    else:
        flash("You don't have the permission to do that...", "danger")
        return redirect(url_for('main.search'))


@users.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(
            email=form.email.data.lower()).first()
        if user:
            try:
                password_match = bcrypt.check_password_hash(
                    user.password, form.password.data)
            except ValueError:
                password_match = False
            if password_match:
                login_user(user, remember=form.remember.data)
                user.last_login = datetime.now()
                db.session.commit()
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))

        flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/admin_login/<int:user_id>')
@login_required
def admin_login(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.is_admin:
        admin = user.is_admin
        login_user(user, remember=False)
        return redirect(url_for('main.admin')) if admin else redirect(url_for('main.home'))


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            # Delete old picture
            if current_user.image_file:
                delete_picture(current_user.image_file)
            # Save new picture
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data.lower()
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for('users.account'))  # Post-Get-Redirect-Pattern
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/p/<string:username>")
@users.route("/p/<string:username>/<int:active_template_name_id>")
def profile(username, active_template_name_id=None):
    user = User.query.filter_by(username=username).one()
    image_file = url_for(
        'static', filename='profile_pics/' + user.image_file)

    return render_template(
        'user_profile.html',
        title=user.username,
        user=user,
        image_file=image_file)


@users.route('/reset_password', methods=["GET", "POST"])
def reset_request():
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/admin_reset_password/<int:user_id>')
def admin_password_reset(user_id):
    user = User.query.get_or_404(user_id)
    token = user.get_reset_token()
    flash(f"Reset Link for user {user}:", 'success')
    flash(f"{url_for('users.reset_password', token=token, _external=True)}", 'success')
    return redirect(url_for('main.admin'))


@users.route('/reset_password/<token>', methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)

    if user is None:
        flash("That is an invalid or expired token", 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title="Teset Password", form=form)

Flask_Basic_With_User_Authentication/template_name/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<h1>Generic WebApp Template with User Authentication</h1>

    <h3>Developer: Kahitar</h3>
    <b>Contact:</b> <a href= "mailto:kahitar_productions@gmail.com">kahitar_productions@gmail.com</a>

    </br>
    <b>Other tools</b></br>
    - <a href="https://github.com/Kahitar/TFTScoutAssist">TFT Scout Assist</a>

    </br></br>
    <h3>Attributions</h3>
    Icons from <a href="https://www.iconsdb.com/">iconsdb.com</a>

{% endblock content %}

Flask_Basic_With_User_Authentication/template_name/templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
	  <div class="media">
			<img class="rounded-circle account-img" src="{{ image_file }}">
			<div class="media-body">
			  <h2 class="account-heading">{{ current_user.username }}</h2>
			  <p class="text-secondary">{{ current_user.email }}</p>
			</div>
	  </div>
		<form method="POST" action="" enctype="multipart/form-data"> <!-- encoding type for picture field to work correctly (errors are cryptic -->
			{{ form.hidden_tag() }} <!-- FlaskForm.hidden_tag() uses the app's secret key to protect from attacks. Absolutely necessary! -->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Update Account Info</legend>
				<div class="form-group mb-2">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group mb-2">
					{{ form.email.label(class="form-control-label") }}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group mb-2">
					{{ form.picture.label() }}
					{{ form.picture(class="form-control-file") }}
					{% if form.picture.errors %}
						{% for error in form.picture.errors%}
							</br><span class="text-danger">{{ error }}</span></br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

Flask_Basic_With_User_Authentication/template_name/templates/admin_console.html
{% extends "layout.html" %}
{% block content%}
{% if not current_user.is_admin %}
    <h1>You don't have permission to see this site.</h1>
{% else %}
<h1>Search for Users</h1>
    <form method="POST" action="" enctype="multipart/form-data" class="form-inline">
        <div class="form-group mb-2">
        {{ search_form.hidden_tag() }} <!-- FlaskForm.hidden_tag() uses the app's secret key to protect from attacks. Absolutely necessary! -->
        {% if search_form.query.errors %}
            {{ search_form.query(class="form-control mr-sm-2") }}
            <div class="invalid-feedback">
                {% for error in search_form.query.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ search_form.query(class="form-control mr-sm-2") }}
        {% endif %}
            {{ search_form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <div>
        <table class="table table-hover">
            <thead>
                <th>Username</th>
                <th>Email</th>
                <th>Last Login</th>
                <th>Admin</th>
                <th colspan="3" class="table-warning">Admin Controls ( Be super careful here! )</th>
            </thead>
            {% for user in users %}
                <tr>
                    <td>
                        <a href="{{ url_for('users.profile', username=user.username) }}">{{ user.username }}</a>
                        {% if user == current_user %}
                        (You)
                        {% endif %}
                    </td>
                    <td>
                        {{user.email }}
                    </td>
                    <td>
                        {% if user.last_login %}
                            {{ user.last_login.strftime('%d.%m.%Y %H:%M') }}
                        {% else %}
                            {{ None }}
                        {% endif %}
                    </td>
                    <td>
                        {% if user.is_admin %}
                            Yes
                    </td>
                            {% if user != current_user %}
                    <td>
                                <a class="btn btn-outline-info btn-sm ml-2" href="{{ url_for('users.revoke_admin', user_id=user.id) }}">Revoke Admin</a>
                            {% else %}
                    <td colspan="2">
                                <small class="text-muted ml-2">(You cannot revoke your own admin rights)</small>
                            {% endif %}
                    </td>
                        {% else %}
                            No
                    </td>
                    <td>
                            <a class="btn btn-outline-danger btn-sm ml-2" href="{{ url_for('users.make_admin', user_id=user.id) }}">Make Admin</a>
                    </td>
                        {% endif %}
                        {% if user != current_user %}
                    <td>
                            <a class="btn btn-outline-info btn-sm ml-2" href="{{ url_for('users.admin_login', user_id=user.id) }}">Login</a>
                            <a class="btn btn-outline-info btn-sm ml-2" href="{{ url_for('users.admin_password_reset', user_id=user.id) }}">Reset Password Token</a>
                    </td>
                            {% if not user.is_admin %}
                    <td>
                                <button type="button" class="btn btn-danger btn-sm ml-2" data-toggle="modal" data-target="#deleteUserModal{{ user.id }}">Delete User Account</button>
                    </td>
                            {% endif %}
                        {% else %}
                    <td>
                            <a class="btn btn-outline-info btn-sm ml-2" href="{{ url_for('users.admin_password_reset', user_id=user.id) }}">Reset Password Token</a>
                    </td>
                        {% endif %}
                </tr>

                <!-- Modal to delete user account -->
                <div class="modal fade" id="deleteUserModal{{ user.id }}" tabindex="-1" role="dialog"
                    aria-labelledby="deleteUserModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteUserModalLabel">Delete User? </br>{{ user }} ?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <form action="{{ url_for('users.delete_user', user_id=user.id) }}" method="POST">
                                    <input class="btn btn-danger" type="submit" value="Delete">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </table>
    </div>
{% endif %}

{% endblock %}

Flask_Basic_With_User_Authentication/template_name/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	 <!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">

	{% if title %}
		<title>Gewichtassistent - {{ title }}</title>
	{% else %}
		<title>Gewichtassistent</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="/">Gewichtassistent</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">

					</div>
					<!-- Navbar Right Side -->
					<div class="navbar-nav">

						{% if current_user.is_admin %}
							<a class="nav-item nav-link" href="{{ url_for('main.admin')}}">Admin Dashboard</a>
						{% endif %}
						{% if current_user.is_authenticated %}
							<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
							<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
						{% else %}
							<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
							<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>

	<main role="main">
	<div class="container">
	  <div class="row">
		<div class="col">
			{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for category, message in messages %}
						<div class="alert alert-{{ category }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
			{% block content %}{% endblock %}
		</div>
	  </div>
	</div>
	<div class="container-fluid">
		<div class="row">
		  <div class="col">
			  {% block content_fluid %}{% endblock %}
		  </div>
		</div>
	  </div>
	</main>

	<footer class="site-footer">
		<nav class="navbar navbar-dark bg-steel fixed-bottom py-0">
			<div class="container">
				<div class="navbar-nav mr-auto">
					<a class="nav-item nav-link" href="https://www.twitch.tv/sologesang" target="_blank">twitch.tv/sologesang</a>
				</div>
				<div class="navbar-nav">
					<a class="nav-item nav-link" href="{{ url_for('main.impressum')}}">Impressum</a>
				</div>
			</div>
		</nav>
	</footer>

	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Flask_Basic_With_User_Authentication/template_name/templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }} <!-- FlaskForm.hidden_tag() uses the app's secret key to protect from attacks. Absolutely necessary! -->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				<div class="form-group mb-2">
					{{ form.email.label(class="form-control-label") }}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group mb-2">
					{{ form.password.label(class="form-control-label") }}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check mb-2">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group mb-2">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted ml-2">
					<!-- <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a> -->
					<a href="{{ url_for('users.reset_request') }}" data-toggle="modal" data-target="#resetPWModal">Forgot Password?</a>
				</small>
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
		</small>
	</div>

	<!-- Reset Password Modal -->
    <div class="modal fade" id="resetPWModal" tabindex="-1" role="dialog" aria-labelledby="resetPWModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		  <div class="modal-content">
			<div class="modal-header">
			  <h5 class="modal-title" id="resetPWModalLabel">Please write a mail to <a href="mailto:kahitar.productions@gmail.com">kahitar.productions@gmail.com</a> with your username and email. We will send you a password reset link.</h5>
			  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			  </button>
			</div>
			<div class="modal-footer">
			  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		  </div>
		</div>
	  </div>
{% endblock content %}

Flask_Basic_With_User_Authentication/template_name/templates/register.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }} <!-- FlaskForm.hidden_tag() uses the app's secret key to protect from attacks. Absolutely necessary! -->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
					<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
					<small id="emailHelp" class="form-text text-muted">Your password is never stored in plain-text and cannot be seen by anyone including developers and site admins.</small>
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}

					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already Have an Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
		</small>
	</div>
{% endblock content %}

Flask_Basic_With_User_Authentication/template_name/templates/reset_password.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }} <!-- FlaskForm.hidden_tag() uses the app's secret key to protect from attacks. Absolutely necessary! -->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group mb-2">
					{{ form.password.label(class="form-control-label") }}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group mb-2">
					{{ form.confirm_password.label(class="form-control-label") }}

					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group mb-2">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

Flask_Basic_With_User_Authentication/template_name/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }} <!-- FlaskForm.hidden_tag() uses the app's secret key to protect from attacks. Absolutely necessary! -->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group mb-2">
					{{ form.email.label(class="form-control-label") }}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors%}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group mb-2">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

Flask_Basic_With_User_Authentication/template_name/templates/user_profile.html
{% extends "layout.html" %}
{% block content %}
    <div class="media ml-2">
        <img class="rounded-circle account-img"
            src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
        <div class="media-body">
            <h1 class="account-heading">{{ user.username }}</h1>
            <h4 class="text-secondary">My Weight</h4>
        </div>
    </div>

{% endblock content %}